// Excel enum constants - manually defined to avoid runtime Excel dependency
export const ExcelBorderLineStyle = [
	"None",
	"Continuous",
	"Dash",
	"DashDot",
	"DashDotDot",
	"Dot",
	"Double",
	"SlantDashDot",
] as const;

export const ExcelUnderlineStyle = ["None", "Single", "Double", "SingleAccountant", "DoubleAccountant"] as const;
export const ExcelBorderWeight = ["Hairline", "Thin", "Medium", "Thick"] as const;

export const ExcelBorderIndex = [
	"EdgeTop",
	"EdgeBottom",
	"EdgeLeft",
	"EdgeRight",
	"InsideVertical",
	"InsideHorizontal",
	"DiagonalDown",
	"DiagonalUp",
] as const;

export const ExcelRangeUnderlineStyle = ["None", "Single", "Double", "SingleAccountant", "DoubleAccountant"] as const;

export const ExcelFillPattern = [
	"None",
	"Solid",
	"Gray50",
	"Gray75",
	"Gray25",
	"Horizontal",
	"Vertical",
	"Down",
	"Up",
	"Checker",
	"SemiGray75",
	"LightHorizontal",
	"LightVertical",
	"LightDown",
	"LightUp",
	"Grid",
	"CrissCross",
	"Gray16",
	"Gray8",
	"LinearGradient",
	"RectangularGradient",
] as const;

export const ExcelHorizontalAlignment = [
	"General",
	"Left",
	"Center",
	"Right",
	"Fill",
	"Justify",
	"CenterAcrossSelection",
	"Distributed",
] as const;

export const EXCEL_CHART_TYPES = [
	"3DArea",
	"3DAreaStacked",
	"3DAreaStacked100",
	"3DBarClustered",
	"3DBarStacked",
	"3DBarStacked100",
	"3DColumn",
	"3DColumnClustered",
	"3DColumnStacked",
	"3DColumnStacked100",
	"3DLine",
	"3DPie",
	"3DPieExploded",
	"Area",
	"AreaStacked",
	"AreaStacked100",
	"BarClustered",
	"BarOfPie",
	"BarStacked",
	"BarStacked100",
	"Boxwhisker",
	"Bubble",
	"Bubble3DEffect",
	"ColumnClustered",
	"ColumnStacked",
	"ColumnStacked100",
	"ConeBarClustered",
	"ConeBarStacked",
	"ConeBarStacked100",
	"ConeCol",
	"ConeColClustered",
	"ConeColStacked",
	"ConeColStacked100",
	"CylinderBarClustered",
	"CylinderBarStacked",
	"CylinderBarStacked100",
	"CylinderCol",
	"CylinderColClustered",
	"CylinderColStacked",
	"CylinderColStacked100",
	"Doughnut",
	"DoughnutExploded",
	"Funnel",
	"Histogram",
	"Invalid",
	"Line",
	"LineMarkers",
	"LineMarkersStacked",
	"LineMarkersStacked100",
	"LineStacked",
	"LineStacked100",
	"Pareto",
	"Pie",
	"PieExploded",
	"PieOfPie",
	"PyramidBarClustered",
	"PyramidBarStacked",
	"PyramidBarStacked100",
	"PyramidCol",
	"PyramidColClustered",
	"PyramidColStacked",
	"PyramidColStacked100",
	"Radar",
	"RadarFilled",
	"RadarMarkers",
	"RegionMap",
	"StockHLC",
	"StockOHLC",
	"StockVHLC",
	"StockVOHLC",
	"Sunburst",
	"Surface",
	"SurfaceTopView",
	"SurfaceTopViewWireframe",
	"SurfaceWireframe",
	"Treemap",
	"Waterfall",
	"XYScatter",
	"XYScatterLines",
	"XYScatterLinesNoMarkers",
	"XYScatterSmooth",
	"XYScatterSmoothNoMarkers",
] as const;
