/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TaskpaneRouteRouteImport } from './routes/taskpane/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TaskpaneIndexRouteImport } from './routes/taskpane/index'
import { Route as TaskpaneSettingsRouteImport } from './routes/taskpane/settings'
import { Route as AuthRedirectRouteImport } from './routes/auth/redirect'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const TaskpaneRouteRoute = TaskpaneRouteRouteImport.update({
  id: '/taskpane',
  path: '/taskpane',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskpaneIndexRoute = TaskpaneIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TaskpaneRouteRoute,
} as any)
const TaskpaneSettingsRoute = TaskpaneSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TaskpaneRouteRoute,
} as any)
const AuthRedirectRoute = AuthRedirectRouteImport.update({
  id: '/auth/redirect',
  path: '/auth/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/taskpane': typeof TaskpaneRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/redirect': typeof AuthRedirectRoute
  '/taskpane/settings': typeof TaskpaneSettingsRoute
  '/taskpane/': typeof TaskpaneIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/redirect': typeof AuthRedirectRoute
  '/taskpane/settings': typeof TaskpaneSettingsRoute
  '/taskpane': typeof TaskpaneIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/taskpane': typeof TaskpaneRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/redirect': typeof AuthRedirectRoute
  '/taskpane/settings': typeof TaskpaneSettingsRoute
  '/taskpane/': typeof TaskpaneIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/taskpane'
    | '/auth/callback'
    | '/auth/redirect'
    | '/taskpane/settings'
    | '/taskpane/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/auth/redirect'
    | '/taskpane/settings'
    | '/taskpane'
  id:
    | '__root__'
    | '/'
    | '/taskpane'
    | '/auth/callback'
    | '/auth/redirect'
    | '/taskpane/settings'
    | '/taskpane/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TaskpaneRouteRoute: typeof TaskpaneRouteRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthRedirectRoute: typeof AuthRedirectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/taskpane': {
      id: '/taskpane'
      path: '/taskpane'
      fullPath: '/taskpane'
      preLoaderRoute: typeof TaskpaneRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taskpane/': {
      id: '/taskpane/'
      path: '/'
      fullPath: '/taskpane/'
      preLoaderRoute: typeof TaskpaneIndexRouteImport
      parentRoute: typeof TaskpaneRouteRoute
    }
    '/taskpane/settings': {
      id: '/taskpane/settings'
      path: '/settings'
      fullPath: '/taskpane/settings'
      preLoaderRoute: typeof TaskpaneSettingsRouteImport
      parentRoute: typeof TaskpaneRouteRoute
    }
    '/auth/redirect': {
      id: '/auth/redirect'
      path: '/auth/redirect'
      fullPath: '/auth/redirect'
      preLoaderRoute: typeof AuthRedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TaskpaneRouteRouteChildren {
  TaskpaneSettingsRoute: typeof TaskpaneSettingsRoute
  TaskpaneIndexRoute: typeof TaskpaneIndexRoute
}

const TaskpaneRouteRouteChildren: TaskpaneRouteRouteChildren = {
  TaskpaneSettingsRoute: TaskpaneSettingsRoute,
  TaskpaneIndexRoute: TaskpaneIndexRoute,
}

const TaskpaneRouteRouteWithChildren = TaskpaneRouteRoute._addFileChildren(
  TaskpaneRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TaskpaneRouteRoute: TaskpaneRouteRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthRedirectRoute: AuthRedirectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
