/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TaskpaneRouteRouteImport } from './routes/taskpane/route'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TaskpaneIndexRouteImport } from './routes/taskpane/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as TaskpaneSignInRouteImport } from './routes/taskpane/sign-in'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsFormatRouteImport } from './routes/settings/format'
import { Route as SettingsSplatRouteImport } from './routes/settings/$'
import { Route as AuthRedirectRouteImport } from './routes/auth/redirect'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const TaskpaneRouteRoute = TaskpaneRouteRouteImport.update({
  id: '/taskpane',
  path: '/taskpane',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskpaneIndexRoute = TaskpaneIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TaskpaneRouteRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const TaskpaneSignInRoute = TaskpaneSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => TaskpaneRouteRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsFormatRoute = SettingsFormatRouteImport.update({
  id: '/format',
  path: '/format',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsSplatRoute = SettingsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const AuthRedirectRoute = AuthRedirectRouteImport.update({
  id: '/auth/redirect',
  path: '/auth/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/taskpane': typeof TaskpaneRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/redirect': typeof AuthRedirectRoute
  '/settings/$': typeof SettingsSplatRoute
  '/settings/format': typeof SettingsFormatRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/taskpane/sign-in': typeof TaskpaneSignInRoute
  '/settings/': typeof SettingsIndexRoute
  '/taskpane/': typeof TaskpaneIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/redirect': typeof AuthRedirectRoute
  '/settings/$': typeof SettingsSplatRoute
  '/settings/format': typeof SettingsFormatRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/taskpane/sign-in': typeof TaskpaneSignInRoute
  '/settings': typeof SettingsIndexRoute
  '/taskpane': typeof TaskpaneIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/taskpane': typeof TaskpaneRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/redirect': typeof AuthRedirectRoute
  '/settings/$': typeof SettingsSplatRoute
  '/settings/format': typeof SettingsFormatRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/taskpane/sign-in': typeof TaskpaneSignInRoute
  '/settings/': typeof SettingsIndexRoute
  '/taskpane/': typeof TaskpaneIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/taskpane'
    | '/auth/callback'
    | '/auth/redirect'
    | '/settings/$'
    | '/settings/format'
    | '/settings/profile'
    | '/taskpane/sign-in'
    | '/settings/'
    | '/taskpane/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/auth/redirect'
    | '/settings/$'
    | '/settings/format'
    | '/settings/profile'
    | '/taskpane/sign-in'
    | '/settings'
    | '/taskpane'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/taskpane'
    | '/auth/callback'
    | '/auth/redirect'
    | '/settings/$'
    | '/settings/format'
    | '/settings/profile'
    | '/taskpane/sign-in'
    | '/settings/'
    | '/taskpane/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  TaskpaneRouteRoute: typeof TaskpaneRouteRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthRedirectRoute: typeof AuthRedirectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/taskpane': {
      id: '/taskpane'
      path: '/taskpane'
      fullPath: '/taskpane'
      preLoaderRoute: typeof TaskpaneRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taskpane/': {
      id: '/taskpane/'
      path: '/'
      fullPath: '/taskpane/'
      preLoaderRoute: typeof TaskpaneIndexRouteImport
      parentRoute: typeof TaskpaneRouteRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/taskpane/sign-in': {
      id: '/taskpane/sign-in'
      path: '/sign-in'
      fullPath: '/taskpane/sign-in'
      preLoaderRoute: typeof TaskpaneSignInRouteImport
      parentRoute: typeof TaskpaneRouteRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/format': {
      id: '/settings/format'
      path: '/format'
      fullPath: '/settings/format'
      preLoaderRoute: typeof SettingsFormatRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/$': {
      id: '/settings/$'
      path: '/$'
      fullPath: '/settings/$'
      preLoaderRoute: typeof SettingsSplatRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/auth/redirect': {
      id: '/auth/redirect'
      path: '/auth/redirect'
      fullPath: '/auth/redirect'
      preLoaderRoute: typeof AuthRedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsSplatRoute: typeof SettingsSplatRoute
  SettingsFormatRoute: typeof SettingsFormatRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsSplatRoute: SettingsSplatRoute,
  SettingsFormatRoute: SettingsFormatRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface TaskpaneRouteRouteChildren {
  TaskpaneSignInRoute: typeof TaskpaneSignInRoute
  TaskpaneIndexRoute: typeof TaskpaneIndexRoute
}

const TaskpaneRouteRouteChildren: TaskpaneRouteRouteChildren = {
  TaskpaneSignInRoute: TaskpaneSignInRoute,
  TaskpaneIndexRoute: TaskpaneIndexRoute,
}

const TaskpaneRouteRouteWithChildren = TaskpaneRouteRoute._addFileChildren(
  TaskpaneRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  TaskpaneRouteRoute: TaskpaneRouteRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthRedirectRoute: AuthRedirectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
